CREATE DATABASE WDP_Project;

USE WDP_Project;

CREATE TABLE IF NOT EXISTS Users (
    UserID INT NOT NULL AUTO_INCREMENT,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    UserName VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (UserID)
);

CREATE TABLE IF NOT EXISTS Category(
    CategoryID INT NOT NULL AUTO_INCREMENT,
    CategoryName VARCHAR(255) NOT NULL,
    CONSTRAINT pk_Category PRIMARY KEY (CategoryID)
);

CREATE TABLE IF NOT EXISTS Journal_Entry (
    EntryID INT NOT NULL AUTO_INCREMENT,
    Content TEXT NOT NULL,
    DateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
    UserID INT NOT NULL,
    CategoryID INT NOT NULL,
    CONSTRAINT pk_Journal_Entry PRIMARY KEY (EntryID),
    CONSTRAINT fk_Users FOREIGN KEY (UserID) REFERENCES Users(UserID),
    CONSTRAINT fk_Category FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID)
);

